### ISSUE TITLE
Add Dockerfile

### ISSUE THREAD

**Issue by emaildanwilson** [hashicorp/vault-service-broker#14]
I'd like to run this broker inside of a docker environment. 
Can you add this to your dockerhub?
Is the correct approach to it to hashicorp/docker-hub-images?

Thank you!

**Comment by emaildanwilson** [comment]
cc @jefferai @sethvargo let me know what you think. I'm happy to do a pull request to add it and update the readme if that is preferred.

**Comment by sethvargo** [comment]
https://hub.docker.com/r/hashicorp/vault-service-broker/
